version: '2'
services:
    web:
        container_name: laliga-api-web
        image: laliga-api-web
        build: ./web
        links:
            - php
        volumes_from:
            - php
        ports:
            - "80:80"
        network_mode: bridge
    php:
        container_name: laliga-api-php
        image: laliga-api-php
        build: ./php
        volumes:
            - ${APP_DIR}:/home/app:cached
        links:
            - dbserver:laliga-api.dbserver
        network_mode: bridge
    dbserver:
        container_name: laliga-api-dbserver
        image: mariadb:10.0
        volumes:
            - ${APP_DB}:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - ${PORT_DB}:3306
        network_mode: bridge
